### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by RuRuTiaSaMa** [LingmoOS/liblingmo#1]
[  1%] Automatic MOC and UIC for target cuteaccounts_qmlplugins
[  1%] Built target cuteaccounts_qmlplugins_autogen
[  2%] Generating user_interface.cpp, user_interface.h
[  2%] Generating user_interface.moc
[  3%] Generating accounts_interface.cpp, accounts_interface.h
[  4%] Generating accounts_interface.moc
[  5%] Building CXX object accounts/CMakeFiles/cuteaccounts_qmlplugins.dir/cuteaccounts_qmlplugins_autogen/mocs_compilation.cpp.o
[  6%] Building CXX object accounts/CMakeFiles/cuteaccounts_qmlplugins.dir/accountsmanager.cpp.o
[  7%] Building CXX object accounts/CMakeFiles/cuteaccounts_qmlplugins.dir/useraccount.cpp.o
[  8%] Building CXX object accounts/CMakeFiles/cuteaccounts_qmlplugins.dir/usersmodel.cpp.o
[  9%] Building CXX object accounts/CMakeFiles/cuteaccounts_qmlplugins.dir/qmlplugins.cpp.o
[ 10%] Building CXX object accounts/CMakeFiles/cuteaccounts_qmlplugins.dir/user_interface.cpp.o
[ 11%] Building CXX object accounts/CMakeFiles/cuteaccounts_qmlplugins.dir/accounts_interface.cpp.o
[ 12%] Linking CXX shared library libcuteaccounts_qmlplugins.so
[ 12%] Built target cuteaccounts_qmlplugins
[ 13%] Automatic MOC and UIC for target cutebluez_qmlplugins
[ 13%] Built target cutebluez_qmlplugins_autogen
[ 14%] Building CXX object bluez/CMakeFiles/cutebluez_qmlplugins.dir/cutebluez_qmlplugins_autogen/mocs_compilation.cpp.o
[ 15%] Building CXX object bluez/CMakeFiles/cutebluez_qmlplugins.dir/declarativemanager.cpp.o
[ 16%] Building CXX object bluez/CMakeFiles/cutebluez_qmlplugins.dir/declarativeadapter.cpp.o
[ 17%] Building CXX object bluez/CMakeFiles/cutebluez_qmlplugins.dir/declarativedevice.cpp.o
[ 18%] Building CXX object bluez/CMakeFiles/cutebluez_qmlplugins.dir/declarativeinput.cpp.o
[ 19%] Building CXX object bluez/CMakeFiles/cutebluez_qmlplugins.dir/declarativemediaplayer.cpp.o
[ 20%] Building CXX object bluez/CMakeFiles/cutebluez_qmlplugins.dir/declarativedevicesmodel.cpp.o
[ 21%] Building CXX object bluez/CMakeFiles/cutebluez_qmlplugins.dir/bluezqtextensionplugin.cpp.o
[ 21%] Building CXX object bluez/CMakeFiles/cutebluez_qmlplugins.dir/applet/devicesproxymodel.cpp.o
[ 22%] Building CXX object bluez/CMakeFiles/cutebluez_qmlplugins.dir/applet/bluetoothagent.cpp.o
[ 23%] Building CXX object bluez/CMakeFiles/cutebluez_qmlplugins.dir/applet/bluetoothmanager.cpp.o
[ 24%] Linking CXX shared library libcutebluez_qmlplugins.so
[ 24%] Built target cutebluez_qmlplugins
[ 25%] Automatic MOC and UIC for target cutempris_qmlplugins
[ 25%] Built target cutempris_qmlplugins_autogen
[ 26%] Building CXX object mpris/CMakeFiles/cutempris_qmlplugins.dir/cutempris_qmlplugins_autogen/mocs_compilation.cpp.o
[ 27%] Building CXX object mpris/CMakeFiles/cutempris_qmlplugins.dir/mpris.cpp.o
[ 28%] Building CXX object mpris/CMakeFiles/cutempris_qmlplugins.dir/mpriscontroller.cpp.o
[ 29%] Building CXX object mpris/CMakeFiles/cutempris_qmlplugins.dir/mprismanager.cpp.o
[ 30%] Building CXX object mpris/CMakeFiles/cutempris_qmlplugins.dir/mprisplayer.cpp.o
[ 31%] Building CXX object mpris/CMakeFiles/cutempris_qmlplugins.dir/mprisplayeradaptor.cpp.o
[ 32%] Building CXX object mpris/CMakeFiles/cutempris_qmlplugins.dir/mprisplayerinterface.cpp.o
[ 33%] Building CXX object mpris/CMakeFiles/cutempris_qmlplugins.dir/mprisrootadaptor.cpp.o
[ 34%] Building CXX object mpris/CMakeFiles/cutempris_qmlplugins.dir/mprisrootinterface.cpp.o
[ 35%] Building CXX object mpris/CMakeFiles/cutempris_qmlplugins.dir/qmlplugins.cpp.o
[ 36%] Building CXX object mpris/CMakeFiles/cutempris_qmlplugins.dir/qtdbusextended/dbusextendedabstractinterface.cpp.o
[ 37%] Building CXX object mpris/CMakeFiles/cutempris_qmlplugins.dir/qtdbusextended/dbusextendedpendingcallwatcher.cpp.o
[ 38%] Linking CXX shared library libcutempris_qmlplugins.so
[ 38%] Built target cutempris_qmlplugins
[ 39%] Automatic MOC and UIC for target cutenm_qmlplugins
[ 39%] Built target cutenm_qmlplugins_autogen
[ 40%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/cutenm_qmlplugins_autogen/mocs_compilation.cpp.o
[ 41%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/appletproxymodel.cpp.o
[ 42%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/activeconnection.cpp.o
[ 43%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/networkitemslist.cpp.o
[ 44%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/networkmodel.cpp.o
[ 45%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/networkmodelitem.cpp.o
[ 46%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/wiressitemsettings.cpp.o
[ 46%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/uiutils.cpp.o
[ 47%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/identitymodel.cpp.o
[ 48%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/handler.cpp.o
[ 49%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/configuration.cpp.o
[ 50%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/enabledconnections.cpp.o
[ 51%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/enums.cpp.o
[ 52%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/wifisettings.cpp.o
[ 53%] Building CXX object networkmanagement/CMakeFiles/cutenm_qmlplugins.dir/qmlplugins.cpp.o
[ 54%] Linking CXX shared library libcutenm_qmlplugins.so
[ 54%] Built target cutenm_qmlplugins
[ 55%] Automatic MOC and UIC for target cutescreen_qmlplugins
[ 55%] Built target cutescreen_qmlplugins_autogen
[ 56%] Building CXX object screen/CMakeFiles/cutescreen_qmlplugins.dir/cutescreen_qmlplugins_autogen/mocs_compilation.cpp.o
In file included from /run/media/rurutiasama/6292981d-0c65-4713-a67f-60612ba16eef/lingmoos/libcute/build/screen/cutescreen_qmlplugins_autogen/EWIEGA46WW/../../../../screen/confighandler.h:23,
                 from /run/media/rurutiasama/6292981d-0c65-4713-a67f-60612ba16eef/lingmoos/libcute/build/screen/cutescreen_qmlplugins_autogen/EWIEGA46WW/moc_confighandler.cpp:10,
                 from /run/media/rurutiasama/6292981d-0c65-4713-a67f-60612ba16eef/lingmoos/libcute/build/screen/cutescreen_qmlplugins_autogen/mocs_compilation.cpp:4:
/usr/include/KF5/KScreen/kscreen/config.h:197:32: 错误：‘std::optional’尚未声明  197 |     void adjustPriorities(std::optional<OutputPtr> keep = std::nullopt);
      |                                ^~~~~~~~
/usr/include/KF5/KScreen/kscreen/config.h:197:40: 错误：expected ‘,’ or ‘...’ before ‘<’ token
  197 |     void adjustPriorities(std::optional<OutputPtr> keep = std::nullopt);
      |                                        ^
make[2]: *** [screen/CMakeFiles/cutescreen_qmlplugins.dir/build.make:76：screen/CMakeFiles/cutescreen_qmlplugins.dir/cutescreen_qmlplugins_autogen/mocs_compilation.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:934：screen/CMakeFiles/cutescreen_qmlplugins.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2

**Comment by ganyuanzhen** [comment]
This should already be fixed. Please use the latest commit.

**Comment by Intro-iu** [comment]
问题来源与std::optional为CXX17新特性，已提交PR
